version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing packages...
  build:
    commands:
      - echo Build started...
      - mkdir -p build
      - cp index.html build/
artifacts:
  files:
    - build//*
