version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Install complete

  build:
    commands:
      - echo Build started
      - mkdir -p build
      - cp index.html build/

artifacts:
  files:
    - '/*'
  base-directory: build
